dist: trusty
sudo: required
# Enable C++ support
language: cpp
services:
  - docker          # docker still needs sudo
# Compiler selection
compiler:
  - gcc
# Limit git depth and submodules
git:
  depth: 1
  submodules: false
# addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-6
#      - g++-6
before_install:
  # install dependencies
  - docker pull lzutao/docker-ibus-unikey
  # for running and testing
  #- sudo apt-get install ibus
  # command to run tests
  # FIXME: add tests
install:
before_script:
script:
  # Link gcc-6 and g++-6 to their standard commands
  # FIXME: Is gcc-6 needed?
  # NOTE: see https://github.com/vn-input/ibus-unikey/issues/9
  #- export CC=gcc-6 CXX=g++-6
  - docker run --rm -v "$TRAVIS_BUILD_DIR":/SRC lzutao/docker-ibus-unikey sh -c "cd /SRC
      && meson builddir --prefix=/usr --libexec=lib/ibus
      && ninja -C builddir install
      && /usr/lib/ibus/ibus-engine-unikey  --version
      && /usr/lib/ibus/ibus-setup-unikey   --version"
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: